# Generated by Django 3.2.7 on 2021-09-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='/static/images/download.png', upload_to='profie_pic'),
        ),
    ]
